---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: Config
- type: document
  path: exampleSite/data/hero.yaml
  label: Hero
- type: document
  path: exampleSite/data/aboutSection.yaml
  label: About
- type: document
  path: exampleSite/data/serviceSection.yaml
  label: Services
- type: document
  path: exampleSite/data/resumeSection.yaml
  label: Resume
- type: document
  path: exampleSite/data/skillSection.yaml
  label: Skills
- type: document
  path: exampleSite/data/testimonialSection.yaml
  label: Testimonials
- type: document
  path: exampleSite/data/blogSection.yaml
  label: Blog Section
- type: document
  path: exampleSite/config.toml
  label: Config File
- type: heading
  label: Contents
- type: directory
  path: exampleSite/content/portfolio
  label: Portfolio
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/contact
  label: Contact
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/blog
  label: Blog
  create: all
  match: "**/*"
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.71.1
