baseURL = "http://webase.tech"
languageCode = "zh-cn"
paginate = 6
theme = "portio"
title = "维贝斯科技"
[[menu.main]]
name = "主页"
url = "#home"
weight = 1
[[menu.main]]
name = "关于我们"
url = "#about"
weight = 2
[[menu.main]]
name = "服务"
url = "#service"
weight = 3
[[menu.main]]
name = "Work"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "发展历程"
url = "#resume"
weight = 5
[[menu.main]]
name = "文章"
url = "#blog"
weight = 6
[[menu.main]]
name = "联系我们"
url = "#contact"
weight = 7
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "近期文章"
url = "#"
weight = 4
[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © webase.tech 2020"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"
[params.address]
address = "3-4 Shibazono Kawaguchi, Saitama, Japan."
email = "hello@example.com"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "+(448) 833 5272 332"
[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
